### PR TITLE
various spelling+grammar fixes in Auto/AI + changed 'addition fuel' to 'additional fuel'

### PR DESCRIPTION
**Pull request by stevenzchen**
I've made some spelling and grammar updates to the Auto and AI sectors. In addition, I changed all uses of "Spend addition fuel ..." to "spend additional fuel ..."

Thanks so much for creating this mod, it's awesome! Keep up the great work.

### CODE REVIEW

**Comment by sleeper-service-CE** [comment]
Hi stevenzchen, thanks for your help! I'm having some trouble resolving some conflict there, my merge tool tells me it appears to be related to the README.md and events.xml,append. I'm not sure how to fix that on my end (I'm no expert on git)... any help would be appreciated (I suspect you pulling those files from the master and then committing again could solve this? Not sure...)

**Comment by stevenzchen** [comment]
No problem. I rebased these two commits off of your most recent master, and there are no conflicts now. The problem was that I edited an old version of README.md and the other file. I removed those changes, should be good now!

Make sure to pull first before merging, I did a force push on my own branch.

**Comment by sleeper-service-CE** [comment]
"Pull is not possible because you have unmerged files."
I'm kind of lost here. I can't pull the master to my local files anymore and I can't push my locals either.

**Comment by stevenzchen** [comment]
I think what's happening is that you're in the middle of a merge, and are trying to pull changes in before the merge is finished.

If you were still in the middle of merging my old commits that had conflicts, you could just try "git merge --abort". This will try to revert the merge conflicts and bring you back to what you started. If that doesn't work, use "git reset --hard HEAD", which'll reset you to your original local, with your most recent commit (hopefully master). If you do this, all the merge conflicts will go away, and hopefully you'll be back to your own local without the conflicts. Then, pull my branch, and try merging it in again.

Let me know if that works.

**Comment by stevenzchen** [comment]
If nothing else works, and you just wanted your local to look like what's on Github right now, you could run "git reset --hard 601a069f", which should set everything straight and make your local copy the exact same as the one that's online right now. The one that's online seems to be correct as far as I know. But this would erase whatever you've currently got that's in conflict.

**Comment by sleeper-service-CE** [comment]
Sweet! git reset --hard HEAD did resolve the problem. I really appreciate your help man, thanks again.

**Comment by stevenzchen** [comment]
Sure, no problem! I'll do some more edits if I have time, and I'll make sure there won't be any conflicts next time before I make a pull request XD

**Pull request merged**
